-- migrate:up

CREATE TABLE api_keys (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    name VARCHAR NOT NULL,
    api_key VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
   CONSTRAINT fk_user
      FOREIGN KEY(user_id) 
	  REFERENCES users(id)
      ON DELETE CASCADE
);

GRANT SELECT, INSERT, UPDATE, DELETE ON api_keys TO trace_application;
GRANT SELECT ON api_keys TO trace_readonly;


-- migrate:down

DROP TABLE api_keys;