-- migrate:up

-- Space objects
CREATE TYPE validation_status AS ENUM('Pending', 'Verified');
CREATE TYPE avoidance_strategy AS ENUM('Thrusting', 'InTrack');
CREATE TYPE manoeuvre_strategy AS ENUM('Impulsive', 'ContinuousElectrical', 'ContinuousChemical');
CREATE TYPE object_type AS ENUM('Manned', 'Unmanned');

CREATE TABLE space_objects
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organisation_id INT NOT NULL,
    confidentiality confidentiality NULL DEFAULT 'Public',
    name VARCHAR NOT NULL,
    object_type object_type NOT NULL DEFAULT 'Unmanned',
    manoeuvrable BOOLEAN NOT NULL,
    manoeuvre_latency INT NOT NULL,
    avoidance_strategy avoidance_strategy,
    manoeuvre_strategy manoeuvre_strategy,
    three_axis_control BOOLEAN,
    object_mass_kg DOUBLE PRECISION,
    ballistic_coefficient DOUBLE PRECISION,
    remaining_fuel_kg DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- Approvals
    validation_status validation_status NOT NULL DEFAULT 'Pending',
    original_id INT,
    CONSTRAINT fk_organisation FOREIGN KEY (organisation_id) REFERENCES organisations(id) ON DELETE CASCADE
);

-- Give access to the application user, the application user has no access to 
-- The sessions table and therefore cannot fake a login.
GRANT SELECT, INSERT, UPDATE ON space_objects TO trace_application;

-- Give access to the readonly user
GRANT SELECT ON space_objects TO trace_readonly;

-- Manage the updated_at column
SELECT updated_at('space_objects');

-- migrate:down
DROP TABLE space_objects;
DROP TYPE validation_status;
DROP TYPE avoidance_strategy;
DROP TYPE manoeuvre_strategy;
DROP TYPE object_type;