-- migrate:up

CREATE TYPE identifier_type AS ENUM ('Cospar', 'Satcat');

CREATE TABLE object_identifiers
(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  space_object_id INT,
  identifier_type identifier_type NOT NULL,
  object_identifier VARCHAR  NOT NULL,
  CONSTRAINT fk_registered FOREIGN KEY (space_object_id) REFERENCES space_objects (id),
  CONSTRAINT uq_catalogue UNIQUE (identifier_type, object_identifier)
);

-- Give access to the application user, the application user has no access to 
-- The sessions table and therefore cannot fake a login.
GRANT SELECT, INSERT, UPDATE ON object_identifiers TO trace_application;

-- Give access to the readonly user
GRANT SELECT ON object_identifiers TO trace_readonly;

-- migrate:down
DROP TABLE object_identifiers;
DROP TYPE identifier_type;