name = "Tech Startup"
description = "Theme to get a landing page, blog and developer documentation running."
license = "MIT"
homepage = "https://github.com/purton-tech/tech-startup-theme"
# The minimum version of Zola required
min_version = "0.1.0"
# An optional live demo URL
demo = "https://cloak.software"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "Ian Purton"
homepage = "https://github.com/purton-tech"